[package]
name = "cargo-binlist"
description = "List all installed binaries with cargo and their versions"
repository = "https://github.com/bircni/cargo-binlist"
version = "0.1.0"
authors = ["bircni"]
edition = "2021"
license = "MIT"
readme = "README.md"
categories = ["development-tools::cargo-plugins"]
keywords = ["cargo", "binlist", "version", "plugin", "cli"]

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.26", features = ["derive"] }
crates_io_api = { version = "0.11.0", default-features = false, features = [
    "rustls",
] }
log = "0.4"
rayon = "1.10.0"
semver = "1.0.24"
simplelog = "0.12"

[lints.rust]
unsafe_code = "forbid"
deprecated = "warn"

[lints.clippy]
cargo = { level = "warn", priority = -1 }
complexity = { level = "warn", priority = -1 }
correctness = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
perf = { level = "warn", priority = -1 }
style = { level = "warn", priority = -1 }
suspicious = { level = "warn", priority = -1 }
multiple_crate_versions = "allow"               # Cannot fix that
